apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-capacity
  namespace: api-custom
  labels:
    app: k8s-capacity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-capacity
  template:
    metadata:
      labels:
        app: k8s-capacity
    spec:
      containers:
      - name: k8s-capacity
        image: ilmal/k8s-capacity-api:latest
        ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-capacity-service
  namespace: api-custom
spec:
  type: NodePort
  selector:
    app: k8s-capacity
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3001
      targetPort: 3001
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30097
